//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Commons.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testing.Commons.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date has to occur later than the start date &apos;{0}&apos;..
        /// </summary>
        internal static string InvertedRange_Template {
            get {
                return ResourceManager.GetString("InvertedRange_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test method needs to be decorated with a &apos;{0}&apos; attribute..
        /// </summary>
        internal static string MissingExternalConfigurationAssemblyAttribute_Template {
            get {
                return ResourceManager.GetString("MissingExternalConfigurationAssemblyAttribute_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string MissingExternalConfigurationAssemblyFile_Template {
            get {
                return ResourceManager.GetString("MissingExternalConfigurationAssemblyFile_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is not an assembly..
        /// </summary>
        internal static string NotAnExternalConfigurationAssembly_Template {
            get {
                return ResourceManager.GetString("NotAnExternalConfigurationAssembly_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only subscriptions and unsubscriptions of events are supported..
        /// </summary>
        internal static string ParseableEventOperation {
            get {
                return ResourceManager.GetString("ParseableEventOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start value of the range must not be greater than its end value..
        /// </summary>
        internal static string UnorderedRangeBounds {
            get {
                return ResourceManager.GetString("UnorderedRangeBounds", resourceCulture);
            }
        }
    }
}
